# Site settings
title: DC Cooper
email: dc.cooper@gmail.com
description: Github.io page for projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dccooper.github.io" # the base hostname & protocol for your site
twitter_username: stoicbuddha
github_username:  dccooper

# Build settings
markdown: kramdown
